spring.application.name=cinesync-backend

# Active profile (default: dev)
spring.profiles.active=dev

# Application configuration
server.port=8080
server.servlet.context-path=/

# Logging configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.karebes.movies.backend=DEBUG

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# OpenAPI/Swagger configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
